name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - tqdm
  - plyfile
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - submodules/fused-ssim
      - opencv-python
      - joblib